name: reviewdog
on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
jobs:
  biome:
    name: runner / Biome
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: mongolyy/reviewdog-action-biome@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          filter_mode: nofilter
          fail_on_error: true
          biome_flags: './projects/ngrx-extension/src'
